# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

serviceType: ClusterIP
servicePort: 80
containerPort: 8080
component: "croc-hunter"
replicas: 3
image: "709275920124.dkr.ecr.eu-west-1.amazonaws.com/mobmarius/croc-hunter"
imageTag: "latest"
imagePullPolicy: "Always"
## If you have a private registry you specify a secret to use
#imagePullSecrets:
cpu: "10m"
memory: "128Mi"
## Ingress settings
ingress:
  enabled: true
  hostname: croc-hunter.dev-api.bank-abc.internal
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  tls: true
## PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
